#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

char * strnident(const char *src) {
    static char strnident_buffer[256];
    char *p = strnident_buffer;
    memset(strnident_buffer, 0, sizeof(strnident_buffer));

    if (isalpha(*src) || *src == '_') {
        *p++ = *src++;
    }

    while (*src) {
        if (isalnum(*src) || *src == '_') {
            *p++ = *src++;
        } else {
            *p++ = '_';
            src++;
        }
    }
    return strnident_buffer;
}

int main(int argc, char **argv) {
    FILE *fin, *fout;
    size_t filelen;
    int linelen;
    char *label;

    if (argc != 4) {
        fprintf(stderr, "Usage: %s <input> <output> <label>\n", argv[0]);
        return 1;
    }

    fin = fopen(argv[1], "rb");
    if (!fin) {
        perror(argv[1]);
        return 1;
    }

    fout = fopen(argv[2], "w");
    if (!fout) {
        perror(argv[2]);
        fclose(fin);
        return 1;
    }

    label = strnident(argv[3]);

    fseek(fin, 0, SEEK_END);
    filelen = ftell(fin);
    rewind(fin);

    fprintf(fout, "/* Generated by BIN2S - please don't edit directly */\n");
    fprintf(fout, "\t.section .rodata\n");
    fprintf(fout, "\t.balign 4\n");
    fprintf(fout, "\t.global %s\n", label);
    fprintf(fout, "%s:\n\t.byte ", label);

    linelen = 0;
    for (size_t i = 0; i < filelen; i++) {
        unsigned char c = fgetc(fin);
        if (i > 0) {
            if (++linelen >= 16) {
                linelen = 0;
                fprintf(fout, "\n\t.byte ");
            } else {
                fprintf(fout, ",");
            }
        }
        fprintf(fout, "%3u", c);
    }

    fprintf(fout, "\n\n\t.global %s_end\n", label);
    fprintf(fout, "%s_end:\n\n", label);

    fprintf(fout, "\t.global %s_size\n", label);
    fprintf(fout, "\t.balign 4\n");
    fprintf(fout, "%s_size: .int %lu\n", label, (unsigned long)filelen);

    fprintf(fout, "\n\n#if defined(__linux__) && defined(__ELF__)\n.section .note.GNU-stack,\"\",%%progbits\n#endif\n");

    fclose(fin);
    fclose(fout);

    return 0;
}
