#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv) {
    if (argc != 3) {
        fprintf(stderr, "Usage: %s <input> <output>\n", argv[0]);
        return 1;
    }

    FILE *fin = fopen(argv[1], "rb");
    if (!fin) {
        perror(argv[1]);
        return 1;
    }

    FILE *fout = fopen(argv[2], "w");
    if (!fout) {
        perror(argv[2]);
        fclose(fin);
        return 1;
    }

    fseek(fin, 0, SEEK_END);
    long filelen = ftell(fin);
    rewind(fin);

    unsigned char *data = malloc(filelen);
    if (!data) {
        fprintf(stderr, "Memory allocation failed\n");
        fclose(fin);
        fclose(fout);
        return 1;
    }

    if (fread(data, 1, filelen, fin) != (size_t)filelen) {
        fprintf(stderr, "Failed to read input file\n");
        free(data);
        fclose(fin);
        fclose(fout);
        return 1;
    }

    fprintf(fout, "/* Generated by bin2c - please don't edit directly */\n");
    fprintf(fout, "unsigned char payload_elf[] = {\n");

    for (long i = 0; i < filelen; i++) {
        if (i % 12 == 0) {
            fprintf(fout, "    ");
        }
        fprintf(fout, "0x%02x", data[i]);
        if (i != filelen - 1) {
            fprintf(fout, ",");
        }
        if (i % 12 == 11 || i == filelen - 1) {
            fprintf(fout, "\n");
        } else {
            fprintf(fout, " ");
        }
    }

    fprintf(fout, "};\n");
    fprintf(fout, "unsigned int size_payload_elf = %ld;\n", filelen);

    free(data);
    fclose(fin);
    fclose(fout);
    return 0;
}
