name: Build OpenTuna Exploit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ps2dev/ps2dev:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install make
      run: apk add --no-cache make
    - name: Build exploit
      env:
        LD_LIBRARY_PATH: /usr/local/ps2dev/lib
      run: make -C exploit
