name: Build OpenTuna Exploit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ps2dev/ps2dev:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install make
      run: apk add --no-cache make
    - name: "Debug: Check environment"
      run: |
        echo "--- ls /usr/local/ps2dev/ee/bin/ ---"
        ls -l /usr/local/ps2dev/ee/bin/
    - name: Build exploit
      env:
        PS2DEV: /usr/local/ps2dev
        PS2SDK: /usr/local/ps2dev/ps2sdk
        GSKIT: /usr/local/ps2dev/gsKit
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/ps2dev/bin:/usr/local/ps2dev/ee/bin:/usr/local/ps2dev/iop/bin:/usr/local/ps2dev/dvp/bin:/usr/local/ps2dev/ps2sdk/bin
      run: make -C exploit
