---
name: Build OpenTuna Exploit

'on': [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --tag opentuna-build:latest

      - name: Build exploit in container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/app \
            -w /app \
            -e PS2DEV=/usr/local/ps2dev \
            -e PS2SDK=/usr/local/ps2dev/ps2sdk \
            -e PATH=/usr/local/ps2dev/bin:/usr/local/ps2dev/ps2sdk/bin:$PATH \
            opentuna-build:latest \
            bash -lc "make -C exploit"

      - uses: actions/upload-artifact@v4
        with:
          name: opentuna-payload
          path: exploit/payload.bin

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: opentuna-payload
          path: .
      - uses: softprops/action-gh-release@fbadcc90e88ecface60a0a0d123795b784ceb239
        # Pinned to commit fbadcc90e88ecface60a0a0d123795b784ceb239 for traceability
        with:
          files: payload.bin
