name: Build OpenTuna Exploit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ps2dev/ps2dev:latest
    env:
      PS2DEV: /usr/local/ps2dev
      PS2SDK: /usr/local/ps2dev/ps2sdk
      GSKIT: /usr/local/ps2dev/gsKit
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/ps2dev/bin:/usr/local/ps2dev/ee/bin:/usr/local/ps2dev/iop/bin:/usr/local/ps2dev/dvp/bin:/usr/local/ps2dev/ps2sdk/bin
      LD_LIBRARY_PATH: /usr/lib
      WINEPREFIX: /tmp/.wine
    steps:
    - uses: actions/checkout@v4
    - name: Install Build Dependencies
      run: apk add --no-cache make gmp mpfr mpc1 wine xvfb git
    - name: Clone ps2sdk-ports
      run: git clone https://github.com/ps2dev/ps2sdk-ports.git
    - name: Build ps2sdk-ports
      run: cd ps2sdk-ports && make && make install
    - name: Build exploit
      run: make -C exploit
