name: Build OpenTuna Exploit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ps2dev/ps2dev:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Build Dependencies
      run: apk add --no-cache make gmp mpfr mpc1 wine
    - name: Build exploit
      run: make -C exploit
