name: Build OpenTuna Exploit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ps2dev/ps2dev:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install make
      run: apk add --no-cache make
    - name: Debug: List toolchain directory
      run: ls -l /usr/local/ps2dev/ee/bin/
    - name: Build exploit
      run: make -C exploit
