name: Build OpenTuna Exploit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ps2dev/ps2dev:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install make
      run: apk add --no-cache make
    - name: "Debug: Check environment"
      run: |
        echo "--- PATH ---"
        echo $PATH
        echo "--- ls /usr/local/ps2dev/ee/bin/ ---"
        ls -l /usr/local/ps2dev/ee/bin/
    - name: Build exploit
      run: |
        export PS2DEV=/usr/local/ps2dev
        export PS2SDK=$PS2DEV/ps2sdk
        export GSKIT=$PS2DEV/gsKit
        export PATH=$PATH:$PS2DEV/bin:$PS2DEV/ee/bin:$PS2DEV/iop/bin:$PS2DEV/dvp/bin:$PS2SDK/bin
        make -C exploit
