name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.3.0
    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        run: apk add --no-cache build-base
      - name: Set GSKIT environment
        run: echo "GSKIT=$PS2DEV/gsKit" >> $GITHUB_ENV
      - name: Cache ps2-packer
        id: cache-ps2-packer
        uses: actions/cache@v4
        with:
          path: ps2-packer/ps2-packer
          key: ${{ runner.os }}-ps2-packer-${{ hashFiles('ps2-packer/**') }}
      - name: Build and test
        run: ./scripts/ci-smoke.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: elf-artifacts
          path: "**/*.elf"
